### ISSUE TITLE
Duplicate events in ical feed

### ISSUE THREAD

**Issue by teuserer** [netz39/www.netz39.de#157]
the UUIDs of ical events change every time the site is deployed. this could be the cause of the following observation:
 
![Image](https://github.com/user-attachments/assets/bd3012a1-6540-4460-9f1f-66784abd83e5)

There should be only one *hacken* event per week as there is only one event specified:
```yaml
layout: event
title: "hacken"
event:
  start: 2025-03-12 19:30:00
  end: 2025-03-12 21:30:00
  frequency: "WEEKLY"
  interval: 1
author: netz39
```

the other events are artifacts from previous deployments. I'd recommend seeding the UUID with a constant value.

![Image](https://github.com/user-attachments/assets/cf0e01dc-757c-4470-af23-e054f08074c0)
